theme = "gruvbox-dark"

icons = "awesome"

[[block]]
block =  "focused_window"
max_width = 21

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notifier = "i3nag"

[[block]]
block = "memory"
clickable = true
critical_mem = 95
display_type = "memory"
format_mem = "{mem_used}/{mem_total}"
icons = true
interval = 5
warning_mem = 70

[[block]]
block = "cpu"
critical = 95
format = "{utilization} | {frequency}"
info = 30
interval = 5
warning = 60

[[block]]
block = "temperature"
chip = "k10temp-pci-00c3"
collapsed = false
format = "{min}"
good = 40
idle = 60
info = 80
interval = 10
warning = 90

[[block]]
block = "sound"
format = "{volume:3#110} {volume:3}"

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
format = "{percentage}% {time}"
interval = 10

[[block]]
block = "time"
format = "%a %d/%m %R"
interval = 60




